name: perfcast
channels:
  - conda-forge
dependencies:
  - python=3.11
  - platformdirs
  - pexpect
  - libffi
  - python-dateutil
  - nest-asyncio
  - asttokens
  - importlib-metadata
  - debugpy
  - pickleshare
  - appnope
  - packaging
  - jupyter_core
  - exceptiongroup
  - pip
  - setuptools
  - tzdata
  - zeromq
  - stack_data
  - zipp
  - wheel
  - matplotlib-inline
  - tornado
  - ca-certificates
  - parso
  - traitlets
  - ncurses
  - libsqlite
  - python_abi
  - typing_extensions
  - comm
  - libsodium
  - psutil
  - ptyprocess
  - pygments
  - jupyter_client
  - pure_eval
  - pyzmq
  - bzip2
  - importlib_metadata
  - jedi
  - readline
  - wcwidth
  - prompt-toolkit
  - libcxx
  - openssl
  - six
  - ipython
  - tk
  - xz
  - libexpat
  - decorator
  - executing
  - libzlib
  - ipykernel
  - torchvision
  - torchaudio
  - pytorch
  - pyside2

